apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dynomite
  labels:
    run: dynomite
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: dynomite
    spec:
      containers:
      - name: dynomite
        image: v1r3n/dynomite
        ports:
        - containerPort: 8102
          protocol: TCP
        - containerPort: 22122
          protocol: TCP
        - containerPort: 22222
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name:  dynomite-svc
spec:
  selector:
    run:  dynomite
  type:  NodePort
  ports:
  - name:  dyno
    port:  8102
    targetPort:  8102
  - name:  dyno-nonquorum
    port:  22122
    targetPort:  22122