kind: Service
apiVersion: v1
metadata:
  name:  dynomite-svc
spec:
  selector:
    run:  dynomite
  type:  NodePort
  ports:
  - name:  dyno
    port:  8102
    targetPort:  8102
  - name:  dyno-nonquorum
    port:  22122
    targetPort:  22122